# Vector operations

In [1]:
import numpy as np

In [2]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [3]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [4]:
u + v

array([3, 4, 5, 8])

In [5]:
2 * u

array([ 4,  8, 10, 12])

# Multiplication

## Vector by vector multiplication (dot product)

In [6]:
u.shape

(4,)

In [7]:
u.shape[0]

4

In [8]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = .0
    for i in range(n):
        result = result + u[i] * v[i]
        
    return result

In [9]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [10]:
u.dot(v)

np.int64(14)

In [11]:
u @ v

np.int64(14)

## Matrix by vector multiplication

In [12]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [13]:
U.shape

(3, 4)

In [14]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [15]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [16]:
U.dot(v)

array([14,  5,  5])

In [17]:
U @ v

array([14,  5,  5])

## Matrix by matrix multiplication

In [18]:
V = np.array([
    [1, 1, 2],
    [0, .5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [19]:
V.shape

(4, 3)

In [20]:
U.shape

(3, 4)

In [21]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [22]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [23]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [24]:
U @ V

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [25]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
I = np.eye(3)

In [27]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [28]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Matrix Inverse

In [29]:
# Inverse of a matrix works only for square matrices
Vs = V[:3, :]

In [30]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [31]:
Vs_inv = np.linalg.inv(Vs)

In [32]:
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [33]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
Vs_inv @ Vs

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])