In [1]:
import numpy as np

# Creating arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1, 2, 3, 5, 7, 12])

In [6]:
a[2]

np.int64(3)

In [7]:
a[2] = 10

In [8]:
a

array([ 1,  2, 10,  5,  7, 12])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
# python list
l = list(range(3, 10))
l

[3, 4, 5, 6, 7, 8, 9]

In [12]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multidimensional arrays

In [13]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
n[0][1]

np.int64(2)

In [16]:
n[0][1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [17]:
n[0]

array([ 1, 20,  3])

In [18]:
n[2] = [1, 1, 1] # or = np.array([1, 1, 1])
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [19]:
n[:, 1] # return all the rows :, and second column

array([20,  5,  1])

In [20]:
n[:, 2] = np.array([0, 1, 2])
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

# Randomly generated arrays

In [21]:
# Uniform distribution between 0 and 1
np.random.rand(5, 2)

array([[0.51925749, 0.16221249],
       [0.04424784, 0.85864412],
       [0.79218545, 0.68838556],
       [0.54317535, 0.69245741],
       [0.75363444, 0.86008268]])

In [22]:
# define a random seed to always return reproducible random array (pseudo rundom numbers)
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [23]:
# reproducible sample in standard normal distribution
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [24]:
# reproducible matrix of pseudorandom integers between 0 and 100
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operations

In [25]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [26]:
a + 1

array([1, 2, 3, 4, 5])

In [27]:
a * 2

array([0, 2, 4, 6, 8])

In [28]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [29]:
a - 1

array([-1,  0,  1,  2,  3])

In [30]:
10 + (a * 2)

array([10, 12, 14, 16, 18])

In [31]:
(10 + (a * 2)) ** 2

array([100, 144, 196, 256, 324])

In [32]:
a

array([0, 1, 2, 3, 4])

In [33]:
b = (10 + (a * 2)) ** 2 / 100

In [34]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [35]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [36]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [37]:
a / b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

In [38]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

# Comparison operations

In [39]:
a

array([0, 1, 2, 3, 4])

In [40]:
a >= 2

array([False, False,  True,  True,  True])

In [41]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [42]:
a > b

array([False, False,  True,  True,  True])

In [43]:
# a > b is a condition, and we index each element of array a
# yielding all the elements from a that meet the condition
a[a > b]

array([2, 3, 4])

# Summarizing operation

In [44]:
a.min()

np.int64(0)

In [45]:
a.max()

np.int64(4)

In [46]:
a.sum()

np.int64(10)

In [47]:
a.mean()

np.float64(2.0)

In [48]:
a.std()

np.float64(1.4142135623730951)

In [49]:
n.sum()

np.int64(35)

In [50]:
n.min()

np.int64(0)